export const navlink = [
  { name: "Stays", href: "/property-listing" },
  { name: "Flights", href: "/property-listing" },
  { name: "Packages", href: "/property-listing" },
  { name: "Business", href: "/property-listing" },
  { name: "Blog", href: "/blog" },
];

export const destinations = [
  {
    image:"https://images.pexels.com/photos/35269260/pexels-photo-35269260/free-photo-of-historic-dome-of-a-mediterranean-building.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    city: "Paris",
    country: "France",
    propertyCount: 1200,  
    isTopRated: true,
  },
  {
    image:"https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    city: "Tokyo",
    country: "Japan",
    propertyCount: 950,
    isTopRated: false,
  },
  {
    image:"https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    city: "New York",
    country: "USA",
    propertyCount: 1100,
    isTopRated: true,
  },
  {
    image:"https://images.pexels.com/photos/221457/pexels-photo-221457.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    city: "Sydney",
    country: "Australia",
    propertyCount: 800,
    isTopRated: false,  
  },
  {
    image:"https://images.pexels.com/photos/356830/pexels-photo-356830.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    city: "Rome",
    country: "Italy",
    propertyCount: 670,
    isTopRated: true,
  },  
  {
    image:"https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    city: "Barcelona",  
    country: "Spain",
    propertyCount: 720,
    isTopRated: false,
  },
  {
    image:"https://images.pexels.com/photos/338515/pexels-photo-338515.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    city: "Cape Town",
    country: "South Africa",
    propertyCount: 540,
    isTopRated: true,
  },
  {
    image:"https://images.pexels.com/photos/356004/pexels-photo-356004.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    city: "Rio de Janeiro",
    country: "Brazil",
    propertyCount: 610,
    isTopRated: false,
  }
];

export const vacationRentals = [
  {
    image:"https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG90ZWx8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    title: "Luxury Downtown Hotel",
    location: "New York, USA",
    distance: "2 miles from center",
    price: 250,
    type: "Hotel",
    badge: "Popular", 
  },
  {
    image:"https://media.istockphoto.com/id/1302442919/photo/luxury-beach-villa-at-night.jpg?s=2048x2048&w=is&k=20&c=VxpcC7tzzUWCSnMAkkSf25tIifozys2HbYRGKAqx4hw=",
    title: "Beachside Bungalow",
    location: "Malibu, USA",
    distance: "500 feet from beach",
    price: 400,
    type: "Bungalow",
    badge: "Best Seller", 
  },
  {
    image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FiaW4lMjByZW50YWx8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    title: "Cozy Mountain Cabin",
    location: "Aspen, USA",
    distance: "1 mile from ski lifts",
    price: 300,
    type: "Cabin",
    badge: "New",
  },
  {
    image:"https://images.unsplash.com/photo-1494526585095-c41746248156?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFyaXMlMjByZW50YWx8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    title: "Charming City Apartment",
    location: "Paris, France",
    distance: "0.5 miles from center",
    price: 220,
    type: "Apartment",
    badge: "Popular",
  },
];

export const testimonials = [
  {
    id: 1,
    rating: 5,
    testimonial:
      'PikPakGo showed me both hotels and rentals in one search — no surprises at checkout! It saved me hours of switching tabs.',
    name: 'Sarah Jenkins',
    title: 'Verified Traveler',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=2',
  },
  {
    id: 2,
    rating: 5,
    testimonial:
      'Found a stunning villa in Bali at half the price I expected. The comparison view is a game-changer — I could see hotels vs. rentals side by side.',
    name: 'James Thornton',
    title: 'Digital Nomad',
    image: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=2',
  },
  {
    id: 3,
    rating: 5,
    testimonial:
      'Best travel platform I have used. The search results are comprehensive and easy to compare. Booked our family holiday in minutes!',
    name: 'Maria Garcia',
    title: 'Family Traveler',
    image: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=2',
  },
  {
    id: 4,
    rating: 4,
    testimonial:
      'I love how PikPakGo combines flights and accommodations in one place. Planning my Tokyo trip was effortless — highly recommend!',
    name: "Liam O'Connor",
    title: 'Adventure Seeker',
    image: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&dpr=2',
  },
];



export interface Property {
  id: string;
  type: 'HOTEL' | 'RENTAL';
  image: string;
  title: string;
  location: string;
  guests: number;
  rating: number;
  price: number;
  amenities: string[];
  freeCancellation: boolean;
  noPrepayment: boolean;
}

export const mockProperties: Property[] = [
  {
    id: '1',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Azure Bay Resort',
    location: 'Downtown district',
    guests: 2,
    rating: 4.8,
    price: 240,
    amenities: ['Pool', 'Spa'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '2',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Seaside Loft',
    location: 'Downtown district',
    guests: 2,
    rating: 4.9,
    price: 180,
    amenities: ['Entire Home', 'Kitchen'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '3',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/1134176/pexels-photo-1134176.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'City Center Inn',
    location: 'Downtown district',
    guests: 2,
    rating: 4.2,
    price: 120,
    amenities: ['Downtown'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '4',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Mountain Cabin',
    location: 'Downtown district',
    guests: 2,
    rating: 5,
    price: 350,
    amenities: ['Secluded', 'Hot Tub'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '5',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Urban Studio',
    location: 'Downtown district',
    guests: 2,
    rating: 4.5,
    price: 95,
    amenities: ['WiFi', 'Work Friendly'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '6',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Grand Hotel',
    location: 'Downtown district',
    guests: 2,
    rating: 4.9,
    price: 420,
    amenities: ['Luxury', 'Concierge'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '7',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Sunset Beach Resort',
    location: 'Coastal area',
    guests: 4,
    rating: 4.7,
    price: 380,
    amenities: ['Beachfront', 'Pool', 'Restaurant'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '8',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Cozy Cottage',
    location: 'Countryside',
    guests: 3,
    rating: 4.6,
    price: 145,
    amenities: ['Garden', 'Fireplace', 'Pet Friendly'],
    freeCancellation: true,
    noPrepayment: false,
  },
  {
    id: '9',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Metropolitan Suites',
    location: 'City center',
    guests: 2,
    rating: 4.4,
    price: 210,
    amenities: ['Gym', 'Business Center', 'WiFi'],
    freeCancellation: false,
    noPrepayment: true,
  },
  {
    id: '10',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1743231/pexels-photo-1743231.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Lakeside Villa',
    location: 'Lake district',
    guests: 6,
    rating: 4.9,
    price: 560,
    amenities: ['Lake View', 'Entire Home', 'BBQ', 'Boat Access'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '11',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Boutique Downtown Hotel',
    location: 'Downtown district',
    guests: 2,
    rating: 4.8,
    price: 275,
    amenities: ['Rooftop Bar', 'Spa', 'Restaurant'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '12',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1612351/pexels-photo-1612351.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Modern Penthouse',
    location: 'Uptown',
    guests: 4,
    rating: 4.7,
    price: 425,
    amenities: ['City View', 'Kitchen', 'Balcony', 'Parking'],
    freeCancellation: true,
    noPrepayment: false,
  },
  {
    id: '13',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Garden Paradise Hotel',
    location: 'Suburban area',
    guests: 2,
    rating: 4.3,
    price: 165,
    amenities: ['Garden', 'Pool', 'Free Breakfast'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '14',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Luxury Apartment',
    location: 'Financial district',
    guests: 3,
    rating: 4.6,
    price: 310,
    amenities: ['Gym Access', 'Concierge', 'Work Friendly'],
    freeCancellation: false,
    noPrepayment: true,
  },
  {
    id: '15',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/161758/governor-s-mansion-montgomery-alabama-grand-staircase-161758.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Historic Grand Palace',
    location: 'Old town',
    guests: 2,
    rating: 5,
    price: 680,
    amenities: ['Historic', 'Luxury', 'Fine Dining', 'Concierge'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '16',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/2631746/pexels-photo-2631746.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Beach House',
    location: 'Beachfront',
    guests: 8,
    rating: 4.9,
    price: 720,
    amenities: ['Beach Access', 'Pool', 'BBQ', 'Entire Home'],
    freeCancellation: true,
    noPrepayment: false,
  },
  {
    id: '17',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Skyline Tower Hotel',
    location: 'Business district',
    guests: 2,
    rating: 4.5,
    price: 295,
    amenities: ['City View', 'Executive Lounge', 'WiFi'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '18',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Countryside Barn',
    location: 'Rural area',
    guests: 5,
    rating: 4.8,
    price: 190,
    amenities: ['Garden', 'Pet Friendly', 'Fireplace', 'BBQ'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '19',
    type: 'HOTEL',
    image: 'https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Spa & Wellness Resort',
    location: 'Mountain resort area',
    guests: 2,
    rating: 4.9,
    price: 510,
    amenities: ['Spa', 'Hot Springs', 'Yoga', 'Restaurant'],
    freeCancellation: true,
    noPrepayment: true,
  },
  {
    id: '20',
    type: 'RENTAL',
    image: 'https://images.pexels.com/photos/1974596/pexels-photo-1974596.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Designer Loft',
    location: 'Arts district',
    guests: 2,
    rating: 4.7,
    price: 220,
    amenities: ['Modern Design', 'Kitchen', 'Work Friendly'],
    freeCancellation: false,
    noPrepayment: true,
  },
];
